# Generated by Django 4.1.2 on 2022-10-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='imgs',
            new_name='images',
        ),
    ]
