# Generated by Django 4.1.2 on 2022-10-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_imgs_blogpost_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='images',
            new_name='image',
        ),
    ]
